### PR TITLE
meson: On Linux when compiling with gcc, use zlib.map

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
I was playing around with my alwaysfallback wrap mode and encountered issues with symbol visibility, as mentioned in the port commit, I don't know whether that's the best way to handle it but it's non intrusive and worksforme :)

### CODE REVIEW

**Comment by nirbheek** [comment]
Wait, what issues did you encounter? Could you document them in the commit so it doesn't get forgotten 2 years later? :)

**Comment by MathieuDuponchelle** [comment]
sure

**Comment by MathieuDuponchelle** [comment]
Added some more info

**Comment by nirbheek** [comment]
I wonder if the same problem will also happen on Windows. I guess we'll find out eventually.

**Pull request merged**
